apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: my-hello-app
  name: my-node-service
spec:
  ports:
  - name: my-hello-app
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: my-hello-app
  type: LoadBalancer
status:
  loadBalancer: {}
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-hello-app
spec:
  selector:
    matchLabels:
      app: my-hello-app
  replicas: 1
  template:
    metadata:
      labels:
        app: my-hello-app
    spec:
      containers:
      - image: bjayant/my-hello-app:latest
        name: my-hello-app
        ports:
        - name: my-hello-app
          containerPort: 80
        resources: 
          requests:
            cpu: "0.1"
            memory: 128M
          limits:
            cpu: "1.0"
            memory: 512M
      dnsPolicy: ClusterFirst

