apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: mysql-client
  name: mysql-client
spec:
  containers:
  - image: mysql:5.6
    name: mysql-client
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
