apiVersion: v1
kind: Pod
metadata:
  labels:
    app: mysql-pod
  name: mysql-pod
spec:
  containers:
    - image: mysql:8.0
      name: mysql-pod
      ports:
      - containerPort: 3307
      volumeMounts:
      - name: mysql-persistent-storage
        mountPath: /var/lib/mysql
      resources:
        requests:
          cpu: 0.1
          memory: 128M
        limits:
          cpu: 1.0
          memory: 512M
  volumes:
    - name: mysql-persistent-storage
      persistentVolumeClaim:
        claimName: mysql-pv-claim
