apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: py-web-app
  name: py-web-service
spec:
  ports:
  - name: py-web-app
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: py-web-app
  type: LoadBalancer
status:
  loadBalancer: {}
