apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: my-node-app
  name: my-node-service
spec:
  ports:
  - name: my-node-app
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: my-node-app
  type: LoadBalancer
status:
  loadBalancer: {}